apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-dp
  namespace: currency-converter-ns
  labels:
    app: consumer
    tier: consumer-api
spec:
  replicas: 1
  template:
    metadata:
      name: consumer-pod
      labels:
        app: consumer
        tier: consumer-api
    spec:
      containers:
        - name: consumer-container
          image: lucaswilker14/currency-converter-consumer
          ports:
            - containerPort: 8081
              name: spring-api-2
          env:
            - name: RDS_CACHE_TYPE
              valueFrom:
                configMapKeyRef:
                  key: cache
                  name: redis-cm
            - name: RDS_HOST
              valueFrom:
                configMapKeyRef:
                  key: host
                  name: redis-cm
            - name: RDS_PORT
              valueFrom:
                configMapKeyRef:
                  key: port
                  name: redis-cm
            - name: RDS_TTL
              valueFrom:
                configMapKeyRef:
                  key: ttl
                  name: redis-cm

            - name: RMQ_HOST
              valueFrom:
                configMapKeyRef:
                  key: host
                  name: rabbitmq-cm
            - name: RMQ_PORT
              valueFrom:
                configMapKeyRef:
                  key: port
                  name: rabbitmq-cm
            - name: RMQ_USER
              valueFrom:
                configMapKeyRef:
                  key: default-user
                  name: rabbitmq-cm
            - name: RMQ_PASS
              valueFrom:
                configMapKeyRef:
                  key: default-pass
                  name: rabbitmq-cm
  selector:
    matchLabels:
      app: consumer
      tier: consumer-api