apiVersion: v1
kind: Service
metadata:
  name: consumer-svc
  namespace: currency-converter-ns
spec:
  selector:
    app: consumer
    tier: consumer-api
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
  type: NodePort