apiVersion: v1
kind: Service
metadata:
  name: producer-svc
  namespace: currency-converter-ns
spec:
  selector:
    app: producer
    tier: producer-api
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082
  type: NodePort