apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
  namespace: currency-converter-ns
spec:
  selector:
    app: rabbitmq
    tier: amqp
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: amqp
    - port: 15672
      targetPort: 15672
      protocol: TCP
      name: http
  type: ClusterIP