apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: currency-converter-ns
spec:
  selector:
    app: redis
    tier: cache
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  type: ClusterIP