apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cm
  namespace: currency-converter-ns
data:
  cache: "redis"
  host: "redis-svc.currency-converter-ns.svc.cluster.local"
  port: "6379"
  ttl: "1800000" # 30 minutes